<a href="https://colab.research.google.com/github/gnbhub/gnbai20211/blob/master/week3/minseok.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# GnB python ai study week3

### 자동차 기능
    엔진열기
    창문열기

##### 자동차 1
    자동차 무게
    주행거리
    연비
    최대 탑승자 수
    연료

---
### 슈퍼 자동차 추가기능
    천장 창문 열기

###### 슈퍼자동차

# UML
|UML| |
|--|--|
|CAR|
|속성들|
|메소드|

클래스 : car supercar
<br>변수 : num_speed

In [15]:
class Car:
    def __init__(self, max_speed, num_person):
        self.max_speed = max_speed
        self.num_person = num_person

        self.is_engine_on = False
        self.current_speed = 0

    def engine_on(self):
        self.is_engine_on = True

    def engine_off(self):
        self.is_engine_on = False
        self.current_speed = 0

    def accelerate(self, speed=10):
        self.current_speed += speed

        if self.current_speed > self.max_speed:
            self.current_speed = self.max_speed

        elif self.current_speed < 0:
            self.current_speed = 0

In [19]:
car1 = Car(80, 4)
car1.accelerate(50)
print(car1.current_speed)

car1.accelerate(50)
print(car1.current_speed)

car1.accelerate(-100)
print(car1.current_speed)

car1.accelerate()
print(car1.current_speed)

50
80
0
10


In [16]:
car1.current_speed

0

In [32]:
class SuperCar(Car):
    
    def __init__(self, max_speed, num_person, brand):
        super().__init__(max_speed, num_person)
    # Car.__init__(self, max_speed, num_person)
    # super()으로 하던 아래 주석처리로 하던 상관없음
        self.brand = brand

    
    pass

In [33]:
super_car1 = SuperCar(300,2,'audi')

In [34]:
super_car1.accelerate(50)
print(super_car1.current_speed)

super_car1.brand

50


'audi'

In [22]:
help(SuperCar)

Help on class SuperCar in module __main__:

class SuperCar(Car)
 |  SuperCar(max_speed, num_person)
 |  
 |  Method resolution order:
 |      SuperCar
 |      Car
 |      builtins.object
 |  
 |  Methods inherited from Car:
 |  
 |  __init__(self, max_speed, num_person)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  accelerate(self, speed=10)
 |  
 |  engine_off(self)
 |  
 |  engine_on(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from Car:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



# 3주차
# 라이브러리 사용법

1. NumPy <br>pandas<br>Matplotlib

### NumPy
    N-dimensional array

In [35]:
import numpy as np
import timeit

In [36]:
def sum_for_loop(n=100_000_000):
    result = 0;
    for i in range(n) :
        result +=i
    return result

def sum_built_in(n=100_000_000):
    return sum(range(n))

def sum_numpy(n=100_000_000):
    return np.sum(np.arange(n))

In [38]:
for func in (sum_for_loop, sum_built_in, sum_numpy):
    print(f'{func.__name__}\t{timeit.timeit(func, number=1)}')

sum_for_loop	7.034852467999826
sum_built_in	2.2293261610002446
sum_numpy	0.6019291410002552


numpy 가 가장 빠르니깐 numpy를 가능하다면 쓰자

##### 3차원 행렬 a(456짜리) 선언후
##### a.ndim = 3
##### a.shape = (4,5,6)
##### len(a,shape) = 3
##### a.size = 4**5 **6= 120개 나옴
##### 구성요소 하나가 int 64인경우   a.dtype = numpy.int64
##### a.itemsize = 120 * 64 = 7680B


In [41]:
a = np.array([[1,2,3],
              [4,5,6]])

print(f'type(a) {type(a)}')
print(f'a.ndim  {a.ndim}')

type(a) <class 'numpy.ndarray'>
a.ndim  2


In [43]:
b = np.array([1,2,3,4,5,6])
print(b)

[1 2 3 4 5 6]


In [44]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
np.ones((2,3,4), dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [46]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [47]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [52]:
a = np.arange(6)

b = np.arange(6)

In [54]:
c = a+b

In [59]:
a %2 == 0
print('이 부분이 중요함')

이 부분이 중요함


In [56]:
a **2

array([ 0,  1,  4,  9, 16, 25])

In [57]:
c

array([ 0,  2,  4,  6,  8, 10])

In [62]:
a[a%2 == 0]

array([0, 2, 4])

In [63]:
a = np.random.random((3,4))

In [64]:
a

array([[0.36037959, 0.96661434, 0.08460505, 0.06143409],
       [0.49436422, 0.2538275 , 0.6316537 , 0.33711555],
       [0.33339986, 0.68760426, 0.5349336 , 0.88282806]])

In [80]:
print(f'a.min(axis=0)   {a.min(axis=0)}')
print(f'a.max(axis=1)   {a.max(axis=1)}')

a.min(axis=0)   [0.33339986 0.2538275  0.08460505 0.06143409]
a.max(axis=1)   [0.96661434 0.6316537  0.88282806]


In [85]:
a = np.arange(2*3).reshape((2,3))
b = np.arange(3*4).reshape((3,4))
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [83]:
np.matmul(a,b)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [84]:
np.dot(a,b)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [86]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
np.transpose(b)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [88]:
b.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [89]:
b[1,2]

6

In [90]:
b[:,3]

array([ 3,  7, 11])

In [91]:
b[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

# pandas

In [93]:
import pandas as pd

In [95]:
path = '/content/sample_data/california_housing_train.csv'

In [96]:
df_train = pd.read_csv(path)

In [99]:
type(df_train)

pandas.core.frame.DataFrame

In [98]:
df_train

longitude  latitude  ...  median_income  median_house_value
0        -114.31     34.19  ...         1.4936             66900.0
1        -114.47     34.40  ...         1.8200             80100.0
2        -114.56     33.69  ...         1.6509             85700.0
3        -114.57     33.64  ...         3.1917             73400.0
4        -114.57     33.57  ...         1.9250             65500.0
...          ...       ...  ...            ...                 ...
16995    -124.26     40.58  ...         2.3571            111400.0
16996    -124.27     40.69  ...         2.5179             79000.0
16997    -124.30     41.84  ...         3.0313            103600.0
16998    -124.30     41.80  ...         1.9797             85800.0
16999    -124.35     40.54  ...         3.0147             94600.0

[17000 rows x 9 columns]

In [100]:
df_train['median_income']

0        1.4936
1        1.8200
2        1.6509
3        3.1917
4        1.9250
          ...  
16995    2.3571
16996    2.5179
16997    3.0313
16998    1.9797
16999    3.0147
Name: median_income, Length: 17000, dtype: float64

In [101]:
df_train.head()

longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0

[5 rows x 9 columns]

In [103]:
df_train.describe()
#count에서 빈곳이 있다 -> 그 위치를 찾아 가야됨

longitude      latitude  ...  median_income  median_house_value
count  17000.000000  17000.000000  ...   17000.000000        17000.000000
mean    -119.562108     35.625225  ...       3.883578       207300.912353
std        2.005166      2.137340  ...       1.908157       115983.764387
min     -124.350000     32.540000  ...       0.499900        14999.000000
25%     -121.790000     33.930000  ...       2.566375       119400.000000
50%     -118.490000     34.250000  ...       3.544600       180400.000000
75%     -118.000000     37.720000  ...       4.767000       265000.000000
max     -114.310000     41.950000  ...      15.000100       500001.000000

[8 rows x 9 columns]