<a href="https://colab.research.google.com/github/gnbhub/gnbai20211/blob/master/week3/week3_Bosung.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. NumPy

## 1-1. NumPy
## 1-2. Why do we need NumPy

In [1]:
import numpy as np
import timeit

In [6]:
def sum_for_loop(n=100_000_000): # loop로 계산
    result = 0;
    for i in range(n):
        result += i
    return result

def sum_built_in(n=100_000_000): # python 내장 함수 사용
    return sum(range(n))

def sum_numpy(n=100_000_000): # numpy 사용
    return np.sum(np.arange(n))

def sum_math(n = 100_000_000):
  return n*(n+1)/2

In [7]:
for func in (sum_for_loop, sum_built_in, sum_numpy, sum_math): # timeit.timeit : 걸린 시간 비교
    print(f'{func.__name__}\t{timeit.timeit(func, number=1)}')

sum_for_loop	6.843449223999983
sum_built_in	2.248461856000006
sum_numpy	0.19109062699999413
sum_math	5.386999987422314e-06


## 1-3. ndarray

###ndarray.ndim 

###ndarray.shape 

###ndarray.size

###ndarray.dtype

in NumPy dimensions are called axes.


    a.ndim = 3
    a.shape = (4, 5, 6)
    len(a.shape) = 3
    a.size = 120 
    a.dtype = numpy.int64
    a.itemsize = 960 Byte



In [13]:
a = np.array([[1, 2, 3],
              [4, 5, 6]], dtype = np.int32)
# 2행 3열 행렬
print(f'type(a)    {type(a)}')
print(f'a.ndim     {a.ndim}')   # number of dimensions(=axes)
print(f'a.shape    {a.shape}')  # dimensions of the array
print(f'a.size     {a.size}')   # total number of elements
print(f'a.dtype    {a.dtype}')  # type of the elements
print(f'a.itemsize {a.itemsize}')

type(a)   <class 'numpy.ndarray'>
a.ndim    2
a.shape   (2, 3)
a.size    6
a.dtype   int32
a.itemsize4


In [14]:
b = np.array([1., 2., 3., 4., 5., 6.])
# b = np.array([1, 2, 3, 4, 5, 6], dtype=float)

print(f'type(b)   {type(b)}')
print(f'b.ndim    {b.ndim}')   # number of dimensions(=axes)
print(f'b.shape   {b.shape}')  # dimensions of the array
print(f'b.size    {b.size}')   # total number of elements
print(f'b.dtype   {b.dtype}')  # type of the elements

type(b)   <class 'numpy.ndarray'>
b.ndim    1
b.shape   (6,)
b.size    6
b.dtype   float64


## 1-4. Array creation

###1) from a regular python list or tuple

In [15]:
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

###2) Using NumPy functions

In [16]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((2, 3, 4), dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [18]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [19]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

###3) np.random

In [21]:
np.random.rand(2, 3)

array([[0.02463056, 0.80557378, 0.46405842],
       [0.57555427, 0.28416321, 0.71375623]])

In [22]:
np.random.rand(2, 3) # standard normal distribution

array([[0.27702942, 0.6608738 , 0.96944375],
       [0.46956032, 0.44518699, 0.09707244]])

In [24]:
np.random.random((2, 3)) # uniform distribution

array([[0.17662957, 0.68531814, 0.69475096],
       [0.9130041 , 0.36272091, 0.36264659]])

In [25]:
np.random.randint(1, 100, (4, 5)) # [low, high)

array([[94, 12,  1, 71, 45],
       [ 3, 61, 32, 88, 20],
       [70, 36, 94, 24, 36],
       [ 9, 29, 32, 49, 46]])

##1-6. Basic operations

In [40]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [27]:
a + 10

array([10, 11, 12, 13, 14, 15])

In [28]:
a * 2

array([ 0,  2,  4,  6,  8, 10])

In [29]:
a / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [30]:
a ** 2

array([ 0,  1,  4,  9, 16, 25])

In [31]:
a < 3

array([ True,  True,  True, False, False, False])

In [41]:
a[a % 2 == 0]

array([0, 2, 4])

### Unary operations

In [42]:
a = np.random.random((3, 4))
a

array([[0.54449763, 0.52980131, 0.25261165, 0.56206083],
       [0.4579663 , 0.28882551, 0.46484281, 0.411097  ],
       [0.53192204, 0.59465448, 0.90515999, 0.62973547]])

In [43]:
print(f'a.sum()   {a.sum()}')
print(f'a.min()   {a.min()}')
print(f'a.max()   {a.max()}')
print(f'a.mean()  {a.mean()}')
print(f'a.std()   {a.std()}')

a.sum()   6.173175012550203
a.min()   0.2526116531529322
a.max()   0.9051599941480839
a.mean()  0.5144312510458503
a.std()   0.16121601367969457


In [45]:
print(f'a.min(axis=0)  {a.min(axis=0)}')  # min of each column 
print(f'a.max(axis=1)  {a.max(axis=1)}')  # max of each row 

# 0번 axis : x축 (열)
# 1번 axis : z축 (행)
# 2번 axis : y축 (3차원상)

a.min(axis=0)  [0.4579663  0.28882551 0.25261165 0.411097  ]
a.max(axis=1)  [0.56206083 0.46484281 0.90515999]


### Normalization
$$
(X - min)/(max - min) => [0, 1]
$$

### Standardization
$$
(X - u)/sigma
$$

## 1-7. Matrix operations
### Multiplication


In [49]:
a = np.arange(2*3).reshape((2, 3))
b = np.arange(3*4).reshape((3, 4))
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [47]:
np.matmul(a, b)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [50]:
np.dot(a, b) # 2차원 행렬만 matmul과 동일

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

### Transpose

In [51]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
np.transpose(b)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [53]:
b.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## 1-8. Indexing, Slicing

In [61]:
b
c = [[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]

In [64]:
tpl = (1, 2)

print(b[tpl])
#print(c[1, 2])
print(c[1][2])

6
6


In [65]:
b[:, 3]

array([ 3,  7, 11])

In [66]:
b[1, :]

array([4, 5, 6, 7])

In [67]:
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

# 2. Pandas
## 2-1. Pandas
## 2-2. File IO - csv

In [68]:
import pandas as pd

In [72]:
path = 'sample_data/california_housing_train.csv'

In [74]:
df_train = pd.read_csv(path)
type(df_train)

pandas.core.frame.DataFrame

In [78]:
df_train

longitude  latitude  ...  median_income  median_house_value
0        -114.31     34.19  ...         1.4936             66900.0
1        -114.47     34.40  ...         1.8200             80100.0
2        -114.56     33.69  ...         1.6509             85700.0
3        -114.57     33.64  ...         3.1917             73400.0
4        -114.57     33.57  ...         1.9250             65500.0
...          ...       ...  ...            ...                 ...
16995    -124.26     40.58  ...         2.3571            111400.0
16996    -124.27     40.69  ...         2.5179             79000.0
16997    -124.30     41.84  ...         3.0313            103600.0
16998    -124.30     41.80  ...         1.9797             85800.0
16999    -124.35     40.54  ...         3.0147             94600.0

[17000 rows x 9 columns]

## 2-3. DataFrame

In [79]:
df_train.head()

longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0

[5 rows x 9 columns]

## 2-4. Series

In [84]:
type(df_train['median_income'])

pandas.core.series.Series

In [81]:
df_train['median_income']

0        1.4936
1        1.8200
2        1.6509
3        3.1917
4        1.9250
          ...  
16995    2.3571
16996    2.5179
16997    3.0313
16998    1.9797
16999    3.0147
Name: median_income, Length: 17000, dtype: float64

### data standardization

In [85]:
df_train.head()

longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0

[5 rows x 9 columns]

In [87]:
df_train.describe()

longitude      latitude  ...  median_income  median_house_value
count  17000.000000  17000.000000  ...   17000.000000        17000.000000
mean    -119.562108     35.625225  ...       3.883578       207300.912353
std        2.005166      2.137340  ...       1.908157       115983.764387
min     -124.350000     32.540000  ...       0.499900        14999.000000
25%     -121.790000     33.930000  ...       2.566375       119400.000000
50%     -118.490000     34.250000  ...       3.544600       180400.000000
75%     -118.000000     37.720000  ...       4.767000       265000.000000
max     -114.310000     41.950000  ...      15.000100       500001.000000

[8 rows x 9 columns]

In [88]:
df_train_std = (df_train - df_train.mean()) / df_train.std()

df_train_std.head() # standardization

longitude  latitude  ...  median_income  median_house_value
0   2.619288 -0.671500  ...      -1.252506           -1.210522
1   2.539494 -0.573248  ...      -1.081451           -1.096713
2   2.494610 -0.905436  ...      -1.170071           -1.048430
3   2.489623 -0.928830  ...      -0.362590           -1.154480
4   2.489623 -0.961581  ...      -1.026424           -1.222593

[5 rows x 9 columns]

### data split

In [89]:
target = 'median_house_value'

x_train = df_train_std.drop(target, axis=1).values
y_train = df_train_std[target].values

In [90]:
print(type(x_train))
print(type(y_train))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [91]:
print(x_train.shape)
print(y_train.shape)

(17000, 8)
(17000,)
