<a href="https://colab.research.google.com/github/gnbhub/gnbai20211/blob/master/week3/week3_Karly.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
class Car:
  def __init__(self, max_speed, num_person):
    self.max_speed = max_speed
    self.num_person = num_person

    self.is_engine_on = False
    self.current_speed = 0

  def engine_on(self):
    self.is_engine_on = True

  def engine_off(self):
    self.is_engine_on = False
    self.current_speed = 0

  def accelerate(self, vel=10):
    self.current_speed += vel

    if self.current_speed > self.max_speed :
      self.current_speed = self.max_speed
      
    elif self.current_speed < 0 :
      self.current_speed = 0

  
car1 = Car(80, 4)

In [11]:
car1.accelerate(50)
print(car1.current_speed)

car1.accelerate(50)
print(car1.current_speed)

car1.accelerate(-100)
print(car1.current_speed)

car1.accelerate()
print(car1.current_speed)

50
80
0


In [17]:
class SuperCar(Car):
  def __init__(self, max_speed, num_person, brand):
    super().__init__(max_speed, num_person)
    self.brand = brand

super1 = SuperCar(300, 2, 'audi')
super1.accelerate(50)
print(super1.current_speed)
print(super1.brand)

50
audi


# GNB Python-AI Study
### Week3 : NumPy, Pandas, Matlabplots

In [18]:
import numpy as np
import timeit

def sum_for_loop(n=100_000_000):
  result = 0
  for i in range(n):
    result += i
  return result

def sum_built_in(n=100_000_000):
  return sum(range(n))

def sum_numpy(n=100_000_000):
  return np.sum(np.arange(n))

In [19]:
for func in (sum_for_loop, sum_built_in, sum_numpy):
  print(f'{func.__name__}\t{timeit.timeit(func, number=1)}')

sum_for_loop	6.78683971800001
sum_built_in	2.0844663500001843
sum_numpy	0.4157528569999158


In [20]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(f'type(a) {type(a)}')
print(f'a.ndim  {a.ndim}')
print(f'a.shape {a.shape}')
print(f'a.size  {a.size}')
print(f'a.dtype {a.dtype}')

type(a) <class 'numpy.ndarray'>
a.ndim  2
a.shape (2, 3)
a.size  6
a.dtype int64


In [21]:
b = np.array([1., 2., 3., 4., 5., 6.])

print(f'type(b) {type(b)}')
print(f'b.ndim  {b.ndim}')
print(f'b.shape {b.shape}')
print(f'b.size  {b.size}')
print(f'b.dtype {b.dtype}')

type(b) <class 'numpy.ndarray'>
b.ndim  1
b.shape (6,)
b.size  6
b.dtype float64


In [22]:
np.array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [23]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones((2, 3, 4), dtype = int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [26]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [27]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [28]:
np.random.rand(2, 3)

array([[0.13718887, 0.43611767, 0.18377988],
       [0.8031546 , 0.91315488, 0.21176262]])

In [30]:
np.random.random((2, 3))

array([[0.50818174, 0.84579038, 0.9236682 ],
       [0.17622091, 0.66810033, 0.04261647]])

In [31]:
np.random.randint(1, 100, (4, 5))

array([[62, 13, 94, 54, 46],
       [51, 89, 24, 62,  2],
       [49, 83, 70, 65, 89],
       [66,  4, 86, 67, 86]])

In [32]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [33]:
a + 10

array([10, 11, 12, 13, 14, 15])

In [34]:
a * 2

array([ 0,  2,  4,  6,  8, 10])

In [35]:
a / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [36]:
a ** 2

array([ 0,  1,  4,  9, 16, 25])

In [37]:
a < 3

array([ True,  True,  True, False, False, False])

In [40]:
a = np.random.random((3, 4))
a

array([[0.6536569 , 0.96024496, 0.03828154, 0.05480573],
       [0.63612624, 0.62241431, 0.40955873, 0.48952487],
       [0.29375812, 0.9790206 , 0.69960458, 0.49454302]])

In [41]:
print(f'a.sum()   {a.sum()}')
print(f'a.min()   {a.min()}')
print(f'a.max()   {a.max()}')
print(f'a.mean()  {a.mean()}')
print(f'a.std()   {a.std()}')

a.sum()   6.331539604962119
a.min()   0.038281537776994945
a.max()   0.9790205952134455
a.mean()  0.5276283004135099
a.std()   0.287421155655172


In [42]:
print(f'a.min(axis=0)   {a.min(axis=0)}') # minimum of each column
print(f'a.max(axis=1)   {a.max(axis=1)}') # maximum of each row

a.min(axis=0)   [0.29375812 0.62241431 0.03828154 0.05480573]
a.max(axis=1)   [0.96024496 0.63612624 0.9790206 ]


In [43]:
a = np.arange(2*3).reshape((2,3))
b = np.arange(3*4).reshape((3,4))

In [44]:
np.matmul(a, b)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [45]:
np.dot(a, b)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [46]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
np.transpose(b)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [48]:
b.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [49]:
b[1, 2]

6

In [50]:
b[:, 3]

array([ 3,  7, 11])

In [51]:
b[1, :]

array([4, 5, 6, 7])

In [52]:
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [53]:
import pandas as pd

In [59]:
path = 'sample_data/california_housing_train.csv'

In [60]:
df_train = pd.read_csv(path)
type(df_train)

pandas.core.frame.DataFrame

In [61]:
df_train

longitude  latitude  ...  median_income  median_house_value
0        -114.31     34.19  ...         1.4936             66900.0
1        -114.47     34.40  ...         1.8200             80100.0
2        -114.56     33.69  ...         1.6509             85700.0
3        -114.57     33.64  ...         3.1917             73400.0
4        -114.57     33.57  ...         1.9250             65500.0
...          ...       ...  ...            ...                 ...
16995    -124.26     40.58  ...         2.3571            111400.0
16996    -124.27     40.69  ...         2.5179             79000.0
16997    -124.30     41.84  ...         3.0313            103600.0
16998    -124.30     41.80  ...         1.9797             85800.0
16999    -124.35     40.54  ...         3.0147             94600.0

[17000 rows x 9 columns]

In [62]:
df_train.head()

longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0

[5 rows x 9 columns]

In [63]:
type(df_train['median_income'])

pandas.core.series.Series

In [64]:
df_train.head()

longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0

[5 rows x 9 columns]

In [65]:
df_train_std = (df_train - df_train.mean()) / df_train.std()
df_train_std.head()

longitude  latitude  ...  median_income  median_house_value
0   2.619288 -0.671500  ...      -1.252506           -1.210522
1   2.539494 -0.573248  ...      -1.081451           -1.096713
2   2.494610 -0.905436  ...      -1.170071           -1.048430
3   2.489623 -0.928830  ...      -0.362590           -1.154480
4   2.489623 -0.961581  ...      -1.026424           -1.222593

[5 rows x 9 columns]

In [66]:
target = 'median_house_value'

x_train = df_train_std.drop(target, axis=1).values
y_train = df_train_std[target].values

In [67]:
print(type(x_train))
print(type(y_train))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [68]:
print(x_train.shape)
print(y_train.shape)

(17000, 8)
(17000,)
