<a href="https://colab.research.google.com/github/gnbhub/gnbai20211/blob/master/week3/week3-jamin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
class Car:
    def __init__(self, max_speed, num_person):
        self.max_speed = max_speed
        self.num_person = num_person
        
        self.is_engine_on = False
        self.current_speed = 0

#    def __repr__(self):
#       return 'hello'
#
#    def __str__(self):
#        return 'world'

    def engine_on(self):
        self.is_engine_on = True

    def engine_off(self):
        self.is_engine_on = False
        self.current_speed = 0

    def accelerate(self, speed = 10):
        self. current_speed += speed

        if self.current_speed>self.max_speed:
            self.current_speed = self.max_speed

        elif self.current_speed == 0:
            self.current_speed = 0;

In [ ]:
car1 = Car(80, 4)

In [ ]:
car1

In [ ]:
car1.current_speed

0

In [ ]:
class SuperCar(Car):

    def __init__(self, max_speed, num_person, brand):
        super().__init__(max_speed, num_person)
        self.brand = brand


In [ ]:
super_car1 = SuperCar(300, 2, 'audi')

In [ ]:
super_car1.accelerate(50)
print(super_car1.current_speed)

super_car1.brand

50


'audi'

In [ ]:
import numpy as np
import timeit

In [ ]:
def sum_for_loop(n=100_000_000):
    result = 0;
    for i in range(n):
        result += i
    return result

def sum_built_in(n=100_000_000):
    return sum(range(n))

def sum_numpy(n=100_000_000):
    return np.sum(np.arange(n))

def sum_math(n=100_000_000):
    return n*(n+1)/2

In [ ]:
for func in (sum_for_loop, sum_built_in, sum_numpy):
    print(f'{func.__name__}\t{timeit.timeit(func, number=1)}')

sum_for_loop	6.716889683999852
sum_built_in	2.0944810390001294
sum_numpy	0.4618624549998458


In [ ]:
a = np.array([[1,2,3],[4,5,6]])

print(f'type(a) {type(a)}')
print(f'a.ndim {a.ndim}')
print(f'a.shape {a.shape}')
print(f'a.size {a.size}')
print(f'a.dtype {a.dtype}')

type(a) <class 'numpy.ndarray'>
a.ndim 2
a.shape (2, 3)
a.size 6
a.dtype int64


In [ ]:
b = np.array([1., 2., 3., 4., 5., 6.])

print(f'type(b)   {type(b)}')
print(f'b.ndim    {b.ndim}')   
print(f'b.shape   {b.shape}')  
print(f'b.size    {b.size}')   
print(f'b.dtype   {b.dtype}') 

type(b)   <class 'numpy.ndarray'>
b.ndim    1
b.shape   (6,)
b.size    6
b.dtype   float64


In [ ]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,3,4), dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [ ]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [ ]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
np.random.rand(2,3)

array([[0.42234073, 0.37486777, 0.42415443],
       [0.40669494, 0.19601666, 0.25611444]])

In [ ]:
np.random.randint(1, 100, (4, 5))

array([[95, 28, 30, 74, 39],
       [48, 81, 17, 32, 25],
       [49, 35, 33, 34, 75],
       [73, 63, 29, 44, 36]])

In [ ]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a + 10

array([10, 11, 12, 13, 14, 15])

In [ ]:
a * 2

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
a/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
a**2

array([ 0,  1,  4,  9, 16, 25])

In [ ]:
a<3

array([ True,  True,  True, False, False, False])

In [ ]:
a % 2 == 0

array([ True, False,  True, False,  True, False])

In [ ]:
a[a%2==0]

array([0, 2, 4])

In [ ]:
a = np.random.random((3, 4))
a

array([[0.06579211, 0.21281349, 0.52111391, 0.91581059],
       [0.68398083, 0.54157103, 0.9105234 , 0.92269202],
       [0.73848662, 0.80861973, 0.21581499, 0.06946989]])

In [ ]:
print(f'a.sum() {a.sum()}')
print(f'a.min() {a.min()}')
print(f'a.max() {a.max()}')
print(f'a.mean() {a.mean()}')
print(f'a.std() {a.std()}')

a.sum() 6.606688602309337
a.min() 0.06579211213460279
a.max() 0.9226920187155543
a.mean() 0.5505573835257781
a.std() 0.3181585874740988


In [ ]:
print(f'a.min(axis = 0) {a.min(axis=0)}')
print(f'a.max(axis = 1) {a.max(axis=1)}')

a.min(axis = 0) [0.06579211 0.21281349 0.21581499 0.06946989]
a.max(axis = 1) [0.91581059 0.92269202 0.80861973]


In [ ]:
a = np.arange(6).reshape((2,3))
b = np.arange(3*4).reshape((3,4))
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.transpose(b)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
b.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
b[1,2]

6

In [ ]:
b[:,3]

array([ 3,  7, 11])

In [ ]:
b[1, :]

array([4, 5, 6, 7])

In [ ]:
import pandas as pd

In [ ]:
path = '/content/sample_data/california_housing_train.csv'

In [ ]:
df_train = pd.read_csv(path)

type(df_train)

pandas.core.frame.DataFrame

In [ ]:
df_train

longitude  latitude  ...  median_income  median_house_value
0        -114.31     34.19  ...         1.4936             66900.0
1        -114.47     34.40  ...         1.8200             80100.0
2        -114.56     33.69  ...         1.6509             85700.0
3        -114.57     33.64  ...         3.1917             73400.0
4        -114.57     33.57  ...         1.9250             65500.0
...          ...       ...  ...            ...                 ...
16995    -124.26     40.58  ...         2.3571            111400.0
16996    -124.27     40.69  ...         2.5179             79000.0
16997    -124.30     41.84  ...         3.0313            103600.0
16998    -124.30     41.80  ...         1.9797             85800.0
16999    -124.35     40.54  ...         3.0147             94600.0

[17000 rows x 9 columns]

In [ ]:
df_train.head()

longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0

[5 rows x 9 columns]

In [ ]:
type(df_train['median_income'])

pandas.core.series.Series

In [ ]:
df_train['median_income']

0        1.4936
1        1.8200
2        1.6509
3        3.1917
4        1.9250
          ...  
16995    2.3571
16996    2.5179
16997    3.0313
16998    1.9797
16999    3.0147
Name: median_income, Length: 17000, dtype: float64

In [ ]:
df_train.describe()

longitude      latitude  ...  median_income  median_house_value
count  17000.000000  17000.000000  ...   17000.000000        17000.000000
mean    -119.562108     35.625225  ...       3.883578       207300.912353
std        2.005166      2.137340  ...       1.908157       115983.764387
min     -124.350000     32.540000  ...       0.499900        14999.000000
25%     -121.790000     33.930000  ...       2.566375       119400.000000
50%     -118.490000     34.250000  ...       3.544600       180400.000000
75%     -118.000000     37.720000  ...       4.767000       265000.000000
max     -114.310000     41.950000  ...      15.000100       500001.000000

[8 rows x 9 columns]